#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[593] =
    {   0,
       34,   34,   38,   36,   34,   35,   33,   36,   32,   34,
       35,   33,   33,   33,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       32,   32,   33,   33,   33,   31,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   32,
       33,   33,   30,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   32,   33,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       32,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   18,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   19,    0,    0,
        0,    0,    0,    0,    0,   17,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        7,    0,   10,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    7,    0,
       10,    0,    0,    0,   29,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   14,

        0,    0,    0,    0,   29,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   15,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    9,    0,    0,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   25,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    6,    5,   28,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    6,
        5,   28,    0,    0,    0,    0,    0,    0,    4,   20,
        0,    0,    0,    0,    0,   12,    0,    0,    0,    0,
        4,   21,    0,   12,    0,   26,    0,    0,    0,    0,
        0,    0,    0,    0,   27,    0,    0,    0,    0,    3,
       22,    0,    0,    0,    0,    0,    3,   23,    0,    0,
        0,    0,    0,   11,    0,   11,   13,    0,    0,   13,
        0,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    7,    8,    8,    8,
        9,    8,    8,    8,    8,    8,    8,   10,    1,   11,
        1,   12,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   19,   21,   19,   19,   22,   23,   19,   24,   25,
       19,   26,   27,   28,   19,   29,   19,   19,   19,   19,
        1,    1,    1,    1,   30,    1,   31,   19,   32,   33,

       34,   19,   35,   19,   36,   19,   19,   37,   38,   39,
       40,   41,   19,   42,   43,   44,   45,   46,   19,   19,
       19,   19,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[47] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_uint16_t yy_base[600] =
    {   0,
        0,   30, 1007, 1008, 1004, 1002,    9,   60, 1000, 1001,
      999,   11,   15,   20,  989,  100,  988,  143,  959,  955,
      955,   30,  962,   86,   13,  961,  951,  951,    5,  961,
      987,  986,   38,   44,   46, 1008,  977,  183,   10,   97,
       96,  106,  101,  118,  103,  102,  108,  107,  140,  131,
       45,  153,  976,  954,  943,  950,  966,  949,  940,  958,
      942,  957,  941,  934,  967,  941,  936,  108,  936,  968,
      114,  145, 1008,  149,  133,  151,  154,  165,  157,  161,
      167,  169,  176,  179,  181,  187,  180,  162,  198,  189,
      194,  201,  202,  208, 1008,  935,  944,  938,  941,  924,

      920,  951,  933,  939,  922,  929,  216,  917,  928,  913,
      920,  916,  951,  225,  226,  213,  219,  224,  225,  203,
      228,  229,  230,  232,  235,  236,  241,  238,  242,  245,
      246,  247, 1008,  919,  919,  912,  923,  906,  913,  931,
      914,  920,  903,  902,  255,  899,  909,  902,  898,  897,
      934,  250,  251,  254,  252,  257,  253,  258,  260,  266,
      270,  277,  279,  286,  281,  283,  288,  289,  291,  897,
      892,  915,  920,  902,  900,  907,  890,  899,  901,  891,
      292,  293,  296,  297,  306,  895,  885,  289,  285,  294,
      314,  301,  311,  166,  316,  317,  312,  322,  328,  330,

      335,  333,  337,  339,  340,  338,  347,  346,  354,  901,
      887,  888,  904,  887,  879,  892,  875,  362,  882,  883,
      344,  341,  351,  342,  353,  881,  871,  868,  873,  883,
      863,  874,  867,  369,  349,  375,  376,  379,  382,  384,
      383,  386,  385,  388,  390,  387,  389,  392,  391,  393,
      394,  396,  861,  872,  862,  879,  862,  889,  870,  872,
      399,  403,  856,  866,  402,  405,  404,  412,  420,  856,
      883,  861,  860,  865,  859,  857,  845,  422,  415,  428,
      425,  429,  876,  431,  430,  432,  433,  434,  435,  438,
      875,  440,  441,  444,  450,  442,  446,  847,  845,  853,

      857,  840, 1008,  452,  847,  453,  451,  834,  839,  460,
      467,  469,  471,  472,  836, 1008,  865,  864,  849,  862,
      828,  841,  473,  476,  474,  477,  475, 1008,  480,  479,
      481,  485,  482,  486,  487, 1008,  859,  858,  492,  857,
      488,  490,  832,  855,  833,  835,  837,  498,  821,  494,
      508,  826,  838,  495,  510,  511,  513,  515,  848, 1008,
     1008,  825, 1008,  826,  820,  520,  844,  518,  522,  526,
      524,  527,  528,  531,  529,  534,  843, 1008, 1008,  536,
     1008,  535,  537,  822, 1008,  813,  543,  818,  549,  805,
      538,  550,  818,  804,  556,  551,  560,  563,  561, 1008,

      804,  816,  819,  565, 1008,  564,  566,  568,  569,  571,
      572,  578,  573,  576, 1008,  579,  577,  580,  809,  802,
      588,  801,  589,  806,  594,  598,  801,  801,  581,  599,
      601,  604,  603,  827,  798,  803,  606,  607,  608,  610,
      613,  612,  616,  619,  618,  621,  824,  624,  625,  794,
      822,  629,  787,  638,  800,  626,  627,  788,  794,  628,
      635,  641,  644,  645, 1008,  814,  786,  649,  815,  651,
      650,  653,  657,  654,  659,  661,  662, 1008,  664,  665,
      790, 1008,  666,  789,  669,  784,  811,  810,  809,  788,
      672,  807,  673,  676,  680,  802,  771,  681, 1008,  683,

      682,  687,  688,  804,  803,  802,  689,  697,  690,  773,
      698,  780,  799,  798, 1008, 1008, 1008,  773,  699,  700,
      707,  702,  796,  771,  708,  710,  711,  794,  793, 1008,
     1008, 1008,  713,  792,  714,  791,  712,  762, 1008, 1008,
      760,  717,  720,  721,  725, 1008,  768,  787,  726,  727,
     1008, 1008,  723, 1008,  734, 1008,  786,  785,  760,  730,
      774,  733,  735,  745, 1008,  765,  764,  739,  740, 1008,
     1008,  733,  745,  746,  760,  758, 1008, 1008,  743,  757,
      756,  744,  742, 1008,  749, 1008, 1008,  748,  747, 1008,
      352, 1008,  787,  355,  789,  791,  793,  109,   57

    } ;

static yyconst flex_int16_t yy_def[600] =
    {   0,
      593,  593,  592,  592,  592,  592,  592,  592,  594,  592,
      592,  592,  592,  592,  595,  596,  597,    8,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
      598,  594,  592,  592,  592,  592,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      597,  595,  595,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,  598,
      592,  592,  592,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  597,  592,   18,   18,   18,   18,   18,

       18,   18,   18,   18,   18,   18,  595,   18,   18,   18,
       18,   18,  599,  592,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  592,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,  595,   18,   18,   18,   18,   18,
      599,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
      595,  595,  595,  595,  595,   18,   18,   18,   18,   18,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,

      596,  596,  596,  596,  596,  596,  596,  596,  596,   18,
       18,   18,   18,   18,   18,   18,   18,  595,   18,   18,
      595,  595,  595,  595,  595,   18,   18,   18,   18,   18,
       18,   18,   18,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,   18,   18,   18,   18,   18,   18,   18,   18,
      595,  595,   18,   18,  595,  595,  595,  595,  595,   18,
       18,   18,   18,   18,   18,   18,   18,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,   18,   18,   18,

       18,   18,  592,  595,   18,  595,  595,   18,   18,  595,
      595,  595,  595,  595,   18,  592,   18,   18,   18,   18,
       18,   18,  596,  596,  596,  596,  596,  592,  596,  596,
      596,  596,  596,  596,  596,  592,  596,  596,  596,  596,
      596,  596,   18,   18,   18,   18,   18,  595,   18,  595,
      595,   18,   18,  595,  595,  595,  595,  595,   18,  592,
      592,   18,  592,   18,   18,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  592,  592,  596,
      592,  596,  596,   18,  592,   18,  595,   18,  595,   18,
      595,  595,   18,   18,  595,  595,  595,  595,  595,  592,

       18,   18,   18,  596,  592,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  592,  596,  596,  596,   18,   18,
      595,   18,  595,   18,  595,  595,   18,   18,  595,  595,
      595,  595,  595,   18,   18,   18,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,   18,
       18,  595,   18,  595,   18,  595,  595,   18,   18,  595,
      595,  595,  595,  595,  592,   18,   18,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  592,  596,  596,
       18,  592,  595,   18,  595,   18,  595,  595,   18,   18,
      595,  595,  595,  595,  595,   18,   18,  596,  592,  596,

      596,  596,  596,  596,  596,  596,  596,  596,  596,   18,
      595,   18,  595,   18,  592,  592,  592,   18,  595,  595,
      595,  595,   18,   18,  596,  596,  596,  596,  596,  592,
      592,  592,  596,  596,  596,   18,  595,   18,  592,  592,
       18,  595,  595,  595,  595,  592,   18,  596,  596,  596,
      592,  592,  596,  592,  596,  592,  595,   18,   18,  595,
      595,  595,  595,   18,  592,  596,  596,  596,  596,  592,
      592,   18,  595,  595,  595,   18,  592,  592,  596,  596,
       18,  595,  595,  592,  596,  592,  592,  595,  595,  592,
      595,    0,  592,  592,  592,  592,  592,  592,  592

    } ;

static yyconst flex_uint16_t yy_nxt[1055] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    7,    7,    4,
        8,    4,    4,   12,   13,   12,   14,   14,   33,   33,
       13,   73,   34,   34,   35,   13,   62,   14,   14,    4,
        4,    5,    6,    4,    4,    4,    4,    7,    7,    4,
        8,    4,    4,   63,   67,   33,   33,   68,   71,   78,
       12,   34,   34,   72,   72,   57,   36,   94,  151,    4,
       15,   15,   15,   15,   15,   15,   16,   15,   15,   15,
       15,   58,   17,   18,   18,   19,   18,   18,   18,   18,
       20,   18,   18,   21,   22,   18,   23,   24,   25,   15,
       18,   18,   26,   18,   18,   18,   18,   18,   27,   18,

       28,   18,   18,   29,   18,   30,   38,   73,   73,   60,
       70,   36,   73,   73,   73,   39,   86,   73,   73,   73,
       40,  114,  114,   41,   42,   61,   43,   44,   45,   73,
      110,   81,   46,   87,   83,   88,  111,   80,   47,   79,
       48,   84,   73,   49,   73,   50,   52,   82,   90,   53,
       89,   73,   72,   72,   36,   15,   84,   85,   18,   53,
       73,   93,   73,   18,   36,   73,   18,   18,   73,   18,
       18,   18,   73,   73,   81,   18,   73,   73,   73,   91,
       73,   18,   92,   18,  119,  236,   18,   73,   18,   38,
       73,   73,   73,  115,   73,  118,   92,  116,   73,  117,

       73,  122,  120,   40,  126,   73,  127,   74,  124,   73,
       75,   45,   73,   73,   73,   46,  125,  121,  123,  133,
       94,   76,  128,  130,   73,  145,   77,   36,   50,  131,
       73,  129,  114,  114,  152,   73,   73,   73,  132,   73,
       73,   73,  159,   73,  154,  157,   73,   73,  153,   73,
      164,  156,   73,   73,  155,  161,   73,   73,   73,  191,
      160,   73,   73,   73,   73,   73,   36,  163,   73,   73,
      181,   73,  166,  158,  162,  182,  198,   73,  183,  184,
      165,   73,  168,  185,  195,  192,  169,  193,   73,  167,
       73,  194,   73,  197,   73,  200,  196,   73,  199,   73,

       73,   39,   73,   36,   36,  230,   40,   36,   36,   41,
      203,  231,   73,  228,  204,  206,  229,   36,  201,  232,
      202,  233,   73,   73,  205,   73,  207,   73,   73,  237,
      208,  221,  209,   73,   40,  222,  225,  223,  224,   73,
      234,   73,  204,  239,   73,  240,   73,  238,   73,   73,
       73,   73,   36,   36,  235,   36,   32,   73,   73,  242,
       73,  243,   36,  571,   36,   73,  249,  241,  244,   87,
      245,  247,  250,   36,  248,  268,  265,  246,   82,  251,
       73,  252,  261,  266,  279,  267,   73,   73,  262,  269,
       73,  278,  281,   73,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   73,   73,  286,   73,  280,  284,
       36,  282,  287,   36,   36,   36,   36,  294,  288,  289,
      307,  283,  290,   36,  285,  306,   73,  296,  291,  293,
      311,   36,  292,   73,  312,  297,   73,  310,  295,   73,
       73,   73,   73,   73,   73,   73,   73,  324,  326,   73,
      332,   73,   73,   73,  313,   73,  330,   73,  331,  314,
      329,   73,   36,   36,   36,  334,  323,  348,  327,  325,
      339,   36,  337,  338,  341,  333,  351,  335,   36,  350,
       36,  340,   36,   36,   73,   73,   73,   73,   73,  342,
       73,   73,   73,   73,  354,  371,   73,   73,   73,   73,

      355,   73,  369,   73,  368,   36,   36,  373,  356,   36,
      374,  366,  372,  358,  357,  367,  370,  380,  389,   36,
      383,   36,   36,  391,   36,  376,   36,  375,  377,   73,
      397,   73,  382,   73,  395,   73,  392,   73,   73,   73,
       73,  399,   73,  398,  409,   73,   73,   73,   73,   36,
      406,  407,  408,  396,   36,  404,  414,  411,  421,  412,
       36,   36,   36,  425,  413,  423,  417,   36,  410,  416,
      426,   36,   36,  418,   36,   73,   73,   73,  429,   73,
       73,  439,   73,   73,   73,  441,  430,   73,   73,   73,
       73,   73,   36,  431,  433,  432,  437,  443,  444,   36,

       36,  440,  454,  438,  445,   36,  449,  448,  452,   36,
       36,  456,   36,  457,   36,   36,  442,   73,   73,   73,
      446,   73,  447,   73,   73,  460,  472,   73,  470,   73,
       73,  461,   73,  474,  475,   73,   73,   36,   36,   36,
       36,  468,  462,  463,  464,  483,   36,  473,  469,   36,
      488,  471,   36,  487,  485,   36,   36,  476,  480,  477,
       73,   73,   73,  479,   73,   73,  491,  500,   73,  502,
       73,  493,   73,   73,  492,   73,   73,   36,  508,  511,
       36,  504,  505,   36,   36,  494,  513,   36,  503,  498,
      495,   36,   73,   73,   73,  501,  526,  507,   73,   73,

       73,   73,  521,  506,  528,  520,  509,  519,   73,   36,
       36,   36,  534,   36,  537,  522,  525,  527,   36,   73,
      533,   73,   73,   36,   73,   73,  549,  529,   36,  557,
      542,   36,   36,  545,   73,  535,   36,   73,   73,  543,
      544,   36,  550,  566,   36,   73,   36,  548,  553,  555,
       73,   73,  560,   36,   73,   36,   36,   36,   36,  556,
      590,  561,  562,  568,  563,  569,  567,  587,  586,  584,
      573,  517,  581,  589,  579,  578,  577,  575,  574,  580,
      582,  583,  585,  588,  576,  482,  591,    9,    9,   15,
       15,   37,   37,   51,   51,  572,  571,  570,  565,  564,

      559,  558,  556,  554,  552,  551,  547,  546,  541,  540,
      539,  538,  536,  532,  531,  530,  524,  523,  385,  518,
      517,  516,  515,  514,  512,  510,  499,  497,  496,  490,
      489,  486,  484,  482,  481,  478,  467,  466,  465,  459,
      458,  455,  453,  451,  450,  436,  435,  434,  428,  427,
      424,  422,  420,  419,  415,  405,  403,  402,  401,  400,
      394,  393,  390,  388,  387,  386,  385,  384,  381,  379,
      378,  365,  364,  363,  362,  361,  360,  359,  353,  352,
      349,  347,  346,  345,  344,  343,  336,  328,  322,  321,
      320,  319,  318,  317,  316,  315,  309,  308,  305,  304,

      303,  302,  301,  300,  299,  298,  277,  276,  275,  274,
      273,  272,  271,  270,  264,  263,  260,  259,  258,  257,
      256,  255,  254,  253,  227,  226,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  592,  190,  189,
      188,  187,  186,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  113,  150,  149,  148,  147,  146,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  113,  112,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   73,   31,
       31,   69,   66,   65,   64,   59,   56,   55,   54,   36,

       36,   11,   10,   31,   11,   10,  592,    3,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592
    } ;

static yyconst flex_int16_t yy_chk[1055] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    7,   12,    7,    7,   12,   12,
       13,   39,   13,   13,   14,   14,   25,   14,   14,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,   25,   29,   33,   33,   29,   34,   39,
       35,   34,   34,   35,   35,   22,   51,   51,  599,    2,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   22,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,   16,   41,   40,   24,
      598,   16,   43,   46,   45,   16,   45,   42,   48,   47,
       16,   71,   71,   16,   16,   24,   16,   16,   16,   44,
       68,   42,   16,   45,   43,   46,   68,   41,   16,   40,
       16,   44,   50,   16,   75,   16,   18,   42,   48,   18,
       47,   49,   72,   72,   18,   18,   75,   44,   18,   52,
       74,   50,   76,   18,   52,   77,   18,   18,   79,   18,
       18,   18,   80,   88,   74,   18,   78,  194,   81,   49,
       82,   18,   49,   18,   81,  194,   18,   83,   18,   38,
       84,   87,   85,   76,   38,   80,   77,   78,   86,   79,

       90,   84,   82,   38,   88,   91,   89,   38,   86,   89,
       38,   38,   92,   93,  120,   38,   87,   83,   85,   94,
       94,   38,   90,   92,  116,  107,   38,  107,   38,   92,
      117,   91,  114,  114,  115,  118,  119,  115,   93,  121,
      122,  123,  122,  124,  117,  120,  125,  126,  116,  128,
      127,  119,  127,  129,  118,  124,  130,  131,  132,  152,
      123,  152,  153,  155,  157,  154,  145,  126,  156,  158,
      145,  159,  129,  121,  125,  145,  159,  160,  145,  145,
      128,  161,  131,  145,  156,  153,  132,  154,  162,  130,
      163,  155,  165,  158,  166,  161,  157,  164,  160,  167,

      168,  164,  169,  181,  182,  189,  164,  183,  184,  164,
      164,  189,  192,  188,  164,  166,  188,  185,  162,  190,
      163,  190,  193,  197,  165,  191,  167,  195,  196,  195,
      168,  181,  169,  198,  191,  182,  185,  183,  184,  199,
      192,  200,  191,  197,  202,  198,  201,  196,  203,  206,
      204,  205,  222,  224,  193,  221,  594,  208,  207,  200,
      235,  201,  223,  591,  225,  209,  208,  199,  202,  204,
      205,  207,  208,  218,  207,  224,  221,  206,  203,  209,
      234,  209,  218,  222,  235,  223,  236,  237,  218,  225,
      238,  234,  237,  239,  241,  240,  243,  242,  246,  244,

      247,  245,  249,  248,  250,  251,  242,  252,  236,  240,
      261,  238,  242,  265,  262,  267,  266,  249,  243,  244,
      262,  239,  245,  268,  241,  261,  279,  251,  246,  248,
      266,  269,  247,  278,  267,  252,  281,  265,  250,  280,
      282,  285,  284,  286,  287,  288,  289,  279,  281,  290,
      287,  292,  293,  296,  268,  294,  285,  297,  286,  269,
      284,  295,  307,  304,  306,  289,  278,  304,  282,  280,
      294,  310,  292,  293,  296,  288,  307,  290,  311,  306,
      312,  295,  313,  314,  323,  325,  327,  324,  326,  297,
      330,  329,  331,  333,  310,  329,  332,  334,  335,  341,

      311,  342,  326,  339,  325,  350,  354,  331,  312,  348,
      332,  323,  330,  314,  313,  324,  327,  339,  348,  351,
      342,  355,  356,  350,  357,  334,  358,  333,  335,  368,
      356,  366,  341,  369,  354,  371,  351,  370,  372,  373,
      375,  358,  374,  357,  371,  376,  382,  380,  383,  391,
      368,  369,  370,  355,  387,  366,  376,  373,  387,  374,
      389,  392,  396,  391,  375,  389,  382,  395,  372,  380,
      392,  397,  399,  383,  398,  406,  404,  407,  395,  408,
      409,  407,  410,  411,  413,  409,  396,  414,  417,  412,
      416,  418,  429,  397,  399,  398,  404,  411,  412,  421,

      423,  408,  423,  406,  413,  425,  418,  417,  421,  426,
      430,  425,  431,  426,  433,  432,  410,  437,  438,  439,
      414,  440,  416,  442,  441,  429,  441,  443,  439,  445,
      444,  430,  446,  443,  444,  448,  449,  456,  457,  460,
      452,  437,  431,  432,  433,  452,  461,  442,  438,  454,
      457,  440,  462,  456,  454,  463,  464,  445,  449,  446,
      468,  471,  470,  448,  472,  474,  460,  470,  473,  472,
      475,  462,  476,  477,  461,  479,  480,  483,  479,  483,
      485,  474,  475,  491,  493,  463,  485,  494,  473,  468,
      464,  495,  498,  501,  500,  471,  500,  477,  502,  503,

      507,  509,  494,  476,  502,  493,  480,  491,  508,  511,
      519,  520,  508,  522,  511,  495,  498,  501,  521,  525,
      507,  526,  527,  537,  533,  535,  526,  503,  542,  537,
      519,  543,  544,  522,  553,  509,  545,  549,  550,  520,
      521,  560,  527,  549,  562,  555,  563,  525,  533,  535,
      568,  569,  542,  583,  579,  582,  573,  574,  589,  588,
      585,  543,  544,  553,  545,  555,  550,  581,  580,  576,
      560,  575,  572,  583,  568,  567,  566,  563,  562,  569,
      573,  574,  579,  582,  564,  561,  589,  593,  593,  595,
      595,  596,  596,  597,  597,  559,  558,  557,  548,  547,

      541,  538,  536,  534,  529,  528,  524,  523,  518,  514,
      513,  512,  510,  506,  505,  504,  497,  496,  492,  490,
      489,  488,  487,  486,  484,  481,  469,  467,  466,  459,
      458,  455,  453,  451,  450,  447,  436,  435,  434,  428,
      427,  424,  422,  420,  419,  403,  402,  401,  394,  393,
      390,  388,  386,  384,  377,  367,  365,  364,  362,  359,
      353,  352,  349,  347,  346,  345,  344,  343,  340,  338,
      337,  322,  321,  320,  319,  318,  317,  315,  309,  308,
      305,  302,  301,  300,  299,  298,  291,  283,  277,  276,
      275,  274,  273,  272,  271,  270,  264,  263,  260,  259,

      258,  257,  256,  255,  254,  253,  233,  232,  231,  230,
      229,  228,  227,  226,  220,  219,  217,  216,  215,  214,
      213,  212,  211,  210,  187,  186,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  151,  150,  149,
      148,  147,  146,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  113,  112,  111,  110,  109,  108,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   70,   69,   67,   66,   65,   64,   63,   62,   61,
       60,   59,   58,   57,   56,   55,   54,   53,   37,   32,
       31,   30,   28,   27,   26,   23,   21,   20,   19,   17,

       15,   11,   10,    9,    6,    5,    3,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  592,  592
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/main.l"
/* Nome: Mariane Tiemi Iguti      RA: 147279
   Nome: Gabriela Akemi Shima     RA: 135819

   EA876 -Trabalho 01 */
#line 6 "src/main.l"

#include <stdlib.h>
#include <string.h>

void yyerror(char *);
#include "y.tab.h"

//
#line 908 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 16 "src/main.l"


#line 1129 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 593 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1008 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 18 "src/main.l"
{printf("Peguei o xml: %s\n", yytext);} // ignora sempre o começo do xml, não considerando o primeiro <xml...>
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "src/main.l"
{printf("Tag sem fechamento : %s\n", yytext);};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "src/main.l"
{ return BELEM_PRESTADOR_TAG; } // token da tag municipio prestador de Belem
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "src/main.l"
{ return BELEM_GERADOR_TAG; } // token da tag municipio gerador de Belem
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "src/main.l"
{ return BELEM_SERVICO_TAG; } // token da tag do valor de servico de Belem
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "src/main.l"
{ return BELEM_ISS_TAG; } // token da tag do valor iss retido de Belem
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "src/main.l"
{ return PARAUAPEBAS_GERADOR_TAG;} // token da tag municipio prestador de Parauapebas
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 "src/main.l"
{ return PARAUAPEBAS_PRESTADOR_TAG;} // token da tag municipio gerador de Parauapebas
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "src/main.l"
{ return PARAUAPEBAS_ISS_TAG;} // token da tag do valor de iss retido de Parauapebas
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "src/main.l"
{ return PARAUAPEBAS_SERVICO_TAG;} // token da tag do valor de servico de Parauapebas
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "src/main.l"
{ return SAOLUIS_SERVICO_TAG;} // token da tag valor de servico de Sao Luis
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "src/main.l"
{ return SAOLUIS_ISS_TAG;} // token da tag valor de servico de Sao Luis
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "src/main.l"
{ return SAOLUIS_MUNICIPIO_TAG;} // token da tag municipio de Sao Luis
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "src/main.l"
{ return SAOLUIS_PRESTADOR_ABRETAG;} // token da abre tag prestador de Sao Luis
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "src/main.l"
{ return SAOLUIS_PRESTADOR_FECHATAG;} // token da fecha tag prestador de Sao Luis
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "src/main.l"
{ return SAOLUIS_GERADOR_ABRETAG;} // token da abre tag tomador de Sao Luis
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "src/main.l"
{ return SAOLUIS_GERADOR_FECHATAG;} // token da fecha tag tomador de Sao Luis
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "src/main.l"
{ /*printf("Entrei em ABRE prestador NOVA LIMA!\n");*/ return CIDADES_PRESTADOR_ABRETAG;} // token abre prestador para cidade NOVA LIMA
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "src/main.l"
{ /*printf("Entrei em FECHA prestador NOVA LIMA!\n");*/ return CIDADES_PRESTADOR_FECHATAG;} // token fecha prestador para cidade NOVA LIMA
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "src/main.l"
{ /*printf("Entrei em ABRE Gerador RIO DE JANEIRO!\n");*/ return CIDADES_GERADOR_ABRETAG;} // token abre gerador para RIO DE JANEIRO
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "src/main.l"
{ /*printf("Entrei em FECHA Gerador RIO DE JANEIRO!\n");*/ return CIDADES_GERADOR_FECHATAG;} // token fecha gerador para RIO DE JANEIRO
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "src/main.l"
{ /*printf("Entrei em ABRE prestador CIDADES!\n");*/ return CIDADES_PRESTADOR_ABRETAG;}// token ABRE_PRESTADOR das cidades CORUMBA, JOAO MONLEVADE, RIO DE JANEIRO
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "src/main.l"
{ /*printf("Entrei em FECHA prestador CIDADES!\n");*/ return CIDADES_PRESTADOR_FECHATAG;}// token da FECHA_PRESTADOR das cidades CORUMBA, JOAO MONLEVADE, RIO DE JANEIRO
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "src/main.l"
{ /*printf("Entrei em ABRE Gerador CIDADES!\n");*/ return CIDADES_GERADOR_ABRETAG;}// token ABRE_GERADOR das cidades CORUMBA, JOAO MONLEVADE, NOVA LIMA
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "src/main.l"
{ /*printf("Entrei em FECHA Gerador CIDADES!\n");*/ return CIDADES_GERADOR_FECHATAG;}// token FECHA_GERADOR das cidades CORUMBA, JOAO MONLEVADE, NOVA LIMA
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "src/main.l"
{ /*printf("Entrei em ABRE CodigoMunicipio!\n");*/return CIDADES_MUNICIPIO_ABRETAG;} // token da tag ABRE_MUNICIPIO das cidades CORUMBA, JOAO MONLEVADE, NOVA LIMA, RIO DE JANEIRO
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "src/main.l"
{ /*printf("Entrei em FECHA CodigoMunicipio!\n");*/return CIDADES_MUNICIPIO_FECHATAG;} // token da tag FECHA_MUNICIPIO das cidades CORUMBA, JOAO MONLEVADE, NOVA LIMA, RIO DE JANEIRO
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "src/main.l"
{ return CIDADES_SERVICO_TAG;} // token da tag valor de servico das cidades CORUMBA, JOAO MONLEVADE, NOVA LIMA, RIO DE JANEIRO
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "src/main.l"
{ return CIDADES_ISS_TAG;} // token da tag valor de iss retido das cidades CORUMBA, JOAO MONLEVADE, NOVA LIMA, RIO DE JANEIRO
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 78 "src/main.l"
{
  printf("fecha:%s\n", yytext);
  return FECHATAG;
  } // token de fecha tag caso geral
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 83 "src/main.l"
{
  printf("abre:%s\n", yytext);
  yylval.string = strdup(yytext); return ABRETAG;
  } // token de abre tag caso geral
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "src/main.l"
{// printf("string:%s\n", yytext);
                                        yylval.string = strdup(yytext);
                                        return STRING; // token de string
                                    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "src/main.l"
{   yylval.string = strdup(yytext);
                                        /*int i; int size = strlen(yytext);
                                        for(i = 0; i < size; i++)
                                        {
                                            if(yytext[i] == ',')
                                                yytext[i] = '.';
                                        }
                                        yylval.number= atof(yytext);*/
                                       //printf("numero:%.2f\n", yylval.number);
                                        return NUMERO; // token para numeros float e ints
                          }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 106 "src/main.l"
;
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 107 "src/main.l"
;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 108 "src/main.l"
;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 110 "src/main.l"
ECHO;
	YY_BREAK
#line 1394 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 593 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 593 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 592);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 110 "src/main.l"



int yywrap()
{
  return 1;
}

